### ISSUE TITLE
Canvas visualisation

### ISSUE THREAD

**Issue by gamb** [alanmacleod/bit-meddler#1]
Would be cool to see bit-meddler in action ;)

**Comment by alanmacleod** [comment]
Another top idea. In fact, earlier this week I was planning to do a sort of random pixel fizzle-fade of two images until they've completely swapped all pixels or something. Forgot to pursue that. Might take a stab this weekend

**Comment by alanmacleod** [comment]
Done.

live demo: https://demos.alanmacleod.eu/bit-meddler/pub/
code:  https://github.com/alanmacleod/bit-meddler-demo
